// Generated by Supabase (generate_typescript_types) for project wsgnjawrmokkvrfgpmpl.
// Regenerate after every migration; do not edit by hand.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.18"
  }
  public: {
    Tables: {
      attempts: {
        Row: {
          code: string | null
          created_at: string
          feedback: string | null
          highlight: Json | null
          hint_level: number | null
          id: string
          input_tokens: number | null
          kind: string
          latency_ms: number | null
          output_tokens: number | null
          session_id: string
          status: string | null
          step_idx: number
        }
        Insert: {
          code?: string | null
          created_at?: string
          feedback?: string | null
          highlight?: Json | null
          hint_level?: number | null
          id?: string
          input_tokens?: number | null
          kind: string
          latency_ms?: number | null
          output_tokens?: number | null
          session_id: string
          status?: string | null
          step_idx: number
        }
        Update: {
          code?: string | null
          created_at?: string
          feedback?: string | null
          highlight?: Json | null
          hint_level?: number | null
          id?: string
          input_tokens?: number | null
          kind?: string
          latency_ms?: number | null
          output_tokens?: number | null
          session_id?: string
          status?: string | null
          step_idx?: number
        }
        Relationships: [
          {
            foreignKeyName: "attempts_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: false
            referencedRelation: "sessions"
            referencedColumns: ["id"]
          },
        ]
      }
      founders: {
        Row: {
          amount_total: number | null
          checkout_session_id: string
          claimed_at: string | null
          claimed_by: string | null
          created_at: string
          currency: string | null
          email: string | null
        }
        Insert: {
          amount_total?: number | null
          checkout_session_id: string
          claimed_at?: string | null
          claimed_by?: string | null
          created_at?: string
          currency?: string | null
          email?: string | null
        }
        Update: {
          amount_total?: number | null
          checkout_session_id?: string
          claimed_at?: string | null
          claimed_by?: string | null
          created_at?: string
          currency?: string | null
          email?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "founders_claimed_by_fkey"
            columns: ["claimed_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      leaks: {
        Row: {
          attempt_no: number
          call_type: string
          created_at: string
          detector: string
          id: string
          raw_response: string
          reason: string
          session_id: string | null
        }
        Insert: {
          attempt_no: number
          call_type: string
          created_at?: string
          detector: string
          id?: string
          raw_response: string
          reason: string
          session_id?: string | null
        }
        Update: {
          attempt_no?: number
          call_type?: string
          created_at?: string
          detector?: string
          id?: string
          raw_response?: string
          reason?: string
          session_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "leaks_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: false
            referencedRelation: "sessions"
            referencedColumns: ["id"]
          },
        ]
      }
      sessions: {
        Row: {
          counts_toward_quota: boolean
          current_step: number
          finished_at: string | null
          hints_used: number
          id: string
          language: string
          largest_paste: number
          paste_count: number
          problem: string
          replay_public: boolean
          share_slug: string
          started_at: string
          status: string
          title: string | null
          trace_ok: boolean | null
          user_id: string
        }
        Insert: {
          counts_toward_quota?: boolean
          current_step?: number
          finished_at?: string | null
          hints_used?: number
          id?: string
          language: string
          largest_paste?: number
          paste_count?: number
          problem: string
          replay_public?: boolean
          share_slug?: string
          started_at?: string
          status?: string
          title?: string | null
          trace_ok?: boolean | null
          user_id: string
        }
        Update: {
          counts_toward_quota?: boolean
          current_step?: number
          finished_at?: string | null
          hints_used?: number
          id?: string
          language?: string
          largest_paste?: number
          paste_count?: number
          problem?: string
          replay_public?: boolean
          share_slug?: string
          started_at?: string
          status?: string
          title?: string | null
          trace_ok?: boolean | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "sessions_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      steps: {
        Row: {
          id: string
          idx: number
          passed_at: string | null
          session_id: string
          success_criteria: string
          task: string
        }
        Insert: {
          id?: string
          idx: number
          passed_at?: string | null
          session_id: string
          success_criteria: string
          task: string
        }
        Update: {
          id?: string
          idx?: number
          passed_at?: string | null
          session_id?: string
          success_criteria?: string
          task?: string
        }
        Relationships: [
          {
            foreignKeyName: "steps_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: false
            referencedRelation: "sessions"
            referencedColumns: ["id"]
          },
        ]
      }
      stripe_events: {
        Row: {
          id: string
          processed_at: string
          type: string
        }
        Insert: {
          id: string
          processed_at?: string
          type: string
        }
        Update: {
          id?: string
          processed_at?: string
          type?: string
        }
        Relationships: []
      }
      trace_chunks: {
        Row: {
          created_at: string
          events: Json
          seq: number
          session_id: string
          step_idx: number
        }
        Insert: {
          created_at?: string
          events: Json
          seq: number
          session_id: string
          step_idx: number
        }
        Update: {
          created_at?: string
          events?: Json
          seq?: number
          session_id?: string
          step_idx?: number
        }
        Relationships: [
          {
            foreignKeyName: "trace_chunks_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: false
            referencedRelation: "sessions"
            referencedColumns: ["id"]
          },
        ]
      }
      usage_ip: {
        Row: {
          count: number
          day: string
          ip_hash: string
        }
        Insert: {
          count?: number
          day: string
          ip_hash: string
        }
        Update: {
          count?: number
          day?: string
          ip_hash?: string
        }
        Relationships: []
      }
      users: {
        Row: {
          created_at: string
          email: string | null
          id: string
          paid: boolean
          paid_at: string | null
          stripe_customer_id: string | null
        }
        Insert: {
          created_at?: string
          email?: string | null
          id: string
          paid?: boolean
          paid_at?: string | null
          stripe_customer_id?: string | null
        }
        Update: {
          created_at?: string
          email?: string | null
          id?: string
          paid?: boolean
          paid_at?: string | null
          stripe_customer_id?: string | null
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      refund_session: {
        Args: { p_ip_hash: string; p_session_id: string }
        Returns: undefined
      }
      start_session: {
        Args: {
          p_ip_hash: string
          p_language: string
          p_limit?: number
          p_problem: string
          p_user_id: string
        }
        Returns: Json
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
